server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: 
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
